
version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      # PC:Contenedor (para conectar, genera un puente)
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
        # PC:Contenedor (para conectar, genera un puente, respaldar)
      - ./mongo:/data/db
